### ISSUE TITLE
CsWin32 generated code does not compile

### ISSUE THREAD

**Issue by youyuanwu** [youyuanwu/service-fabric-cs#1]
Build the main branch has the following error:
```ps1
PS D:\code\cs\service-fabric-cs> dotnet build .\src\ServiceFabric\ServiceFabric.csproj
MSBuild version 17.6.3+07e294721 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
D:\code\cs\service-fabric-cs\src\ServiceFabric\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\ServiceFabric.FABRIC_ERROR_CODE.g.cs(17,37): error CS0234: The type o
r namespace name 'ServiceFabric' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\code\cs\service-fabric-cs\src\ServiceFabric\ServiceFabric.cspr
oj]
D:\code\cs\service-fabric-cs\src\ServiceFabric\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\ServiceFabric.IFabricStringResult.g.cs(17,37): error CS0234: The type
 or namespace name 'ServiceFabric' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\code\cs\service-fabric-cs\src\ServiceFabric\ServiceFabric.cs
proj]
D:\code\cs\service-fabric-cs\src\ServiceFabric\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\ServiceFabric.PInvoke.FabricClient.g.cs(17,37): error CS0234: The typ
e or namespace name 'ServiceFabric' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\code\cs\service-fabric-cs\src\ServiceFabric\ServiceFabric.c
sproj]

Build FAILED.
```
The problem seems to be CsWin32 generated code does not have the right namespace:
```cs
#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Microsoft.ServiceFabric; // This is the namespace in winmd
namespace ServiceFabric // Here the "Microsoft" before "ServiceFabric" is missing
{
	namespace FabricCommon
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.18-beta+dc807e7787")]
		internal interface IFabricStringResult
		{
						[PreserveSig()]
global::Windows.Win32.Foundation.PWSTR get_String();
		}
	}
}
```
winmd file is here: https://github.com/youyuanwu/fabric-metadata/blob/main/.windows/winmd/ServiceFabric.winmd
Its generation proj: https://github.com/youyuanwu/fabric-metadata/blob/main/.metadata/generate.proj

From ILSpy viewer, the winmd looks like this:
![image](https://github.com/youyuanwu/service-fabric-cs/assets/48816116/fdcf8d15-ba6d-4ec3-9804-c775a5f37b2a)

It is unlikely that this is a winmd problem since the windows-rust tool chain can generate the right code; but rather a CsWin32 problem.

Is Microsoft namespace reserved? But it is unlikely since the washington-rs dummy example worked.

**Comment by youyuanwu** [comment]
+ @AArnott @riverar for CsWin32 help.

**Comment by AArnott** [comment]
I tried to repro this locally by adding this winmd to my own project. Cswin32 failed to generate anything, with this error:
![image](https://github.com/youyuanwu/service-fabric-cs/assets/3548/9435ee61-a91f-47cd-9992-358e8e2ad854)
I'm curious why you aren't seeing the same thing.

**Comment by AArnott** [comment]
Ah, my failure happens when allowMarshaling is false. Yours happens when allowMarshaling is true. Both are probably CsWin32 bugs. I'm drilling in.

**Comment by AArnott** [comment]
I have the non-marshaling error fixed. The namespace one I'm still looking at. FWIW though, I wonder if it's a simple matter of the metadata file name not matching the root namespace. If you generate it as `Microsoft.ServiceFabric` I wonder if it would work.

**Comment by AArnott** [comment]
Confirmed: your metadata name and root namespace being different triggered the problem. I have a fix, but as a reasonably permanent workaround you could generate a `Microsoft.ServiceFabric.winmd` file.

**Comment by riverar** [comment]
Nice two bugs down with one issue! Thanks @AArnott @youyuanwu

**Comment by youyuanwu** [comment]
I regenerated the winmd with name "Microsoft.ServiceFabric.winmd" and this fixed the issue. Thanks for the help.
